classifieds/urls.py
"""Defines URL patterns for classifieds."""

from django.urls import path
from . import views

app_name = 'classifieds'

urlpatterns = [
        path('', views.index, name='index'),
        path('categories/', views.categories, name='categories'),
        path('categories/<int:category_id>/', views.category, name='category'),
        path('categories/new_ad/', views.new_ad, name='new_ad'),
        path('ad/<int:ad_id>/', views.individual_ad, name='individual_ad'),
        ]

discussions/urls.py
"""Define URL patterns for discussions."""

from django.urls import path

from . import views

app_name = 'discussions'
urlpatterns = [
        path('', views.index, name='index'),
        path('topics/', views.topics, name='topics'),
        ]

homepage/urls.py
"""Define URL patterns for homepage."""

from django.urls import path

from . import views

app_name = 'homepage'
urlpatterns = [
        path('', views.index, name='index'),
        ]

website/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('classifieds/', include('classifieds.urls')),
    path('discussions/', include('discussions.urls')),
    path('', include('homepage.urls')),
]

classifieds/models.py
"""Models for app classifieds."""

from django.db import models

# Create your models here.


class Category(models.Model):
    """A specified category."""

    category = models.CharField(max_length=100)
    category.disabled = True

    class Meta:
        """Pluralized name of the class."""

        verbose_name_plural = 'categories'

    def __str__(self):
        """Return a string representation of the model."""
        return self.category


class ClassifiedAd(models.Model):
    """A classified ad in a specified category."""

    category = models.ForeignKey(Category, on_delete=models.CASCADE)
    headline = models.CharField(max_length=100)
    body = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)
    email = models.EmailField()

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.headline) > 75:
            return f'{self.headline[:75]}...'
        return self.headline

discussions/models.py
from django.db import models

# Create your models here.

class Topic(models.Model):
    """A general topic user(s) are discussing."""
    text = models.CharField(max_length=200)
    date_added = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        """Return a string representation of the model."""
        return self.text


class Entry(models.Model):
    """A specific entry connected with a specified topic."""
    topic = models.ForeignKey(Topic, on_delete=models.CASCADE)
    text = models.TextField()
    date_added = models.DateTimeField(auto_now_add=True)

    class Meta:
        verbose_name_plural = 'entries'

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.text) < 50:
            return f'{self.text}'
        else:
            return f'{self.text[:50]}...'

homepage/models.py
from django.db import models
from django.conf import settings

# Create your models here.


class Article(models.Model):
    """An news article post."""
    headline = models.CharField(max_length=200)
    content = models.TextField()
    pub_date = models.DateTimeField(auto_now_add=True)
    reporter = models.ForeignKey(settings.AUTH_USER_MODEL,
                                 on_delete=models.CASCADE)

    def __str__(self):
        """Return a string representation of the model."""
        if len(self.headline) > 30:
            headline_str = f'{self.headline[:30]}...'
        else:
            headline_str = f'{self.headline}'
        if len(self.content) > 50:
            content_str = f'\n{self.content[:50]}...'
        else:
            content_str = f'\n{self.content}'

        return headline_str + content_str

classifieds/forms.py
"""Forms used in classified ads."""
from django import forms

from .models import ClassifiedAd


class ClassifiedAdForm(forms.ModelForm):
    """A form to fill out a classified ad."""

    class Meta:
        """Fields included in the form."""

        model = ClassifiedAd
        fields = ['category', 'headline', 'body', 'email']
        labels = {'headline': '', 'body': '', 'email': ''}
        widgets = {'body': forms.Textarea(attrs={'cols': 80})}

classifieds/views.py
"""Views for classifieds."""

from django.shortcuts import render, redirect

from .models import Category, ClassifiedAd
from .forms import ClassifiedAdForm


def index(request):
    """Homepage for classifieds."""
    context = {'title': 'Classifieds - Home'}
    return render(request, 'classifieds/index.html', context)


def categories(request):
    """Show all categories."""
    all_categories = Category.objects.order_by('category')
    # {key:val} where key is the name used in the template, val is the data
    # we're sending to the template!
    context = {'categories': all_categories,
               'title': 'Classifieds - Categories'}
    return render(request, 'classifieds/categories.html', context)


def category(request, category_id):
    """Show a single category and all its classified ads."""
    category_obj = Category.objects.get(id=category_id)
    entries = category_obj.classifiedad_set.order_by('-date_added')
    context = {'category': category_obj, 'entries': entries,
               'title': f'Classifieds - {category_obj}'}
    return render(request, 'classifieds/category.html', context)


def new_ad(request):
    """Add a new ad."""
    if request.method != 'POST':
        # Create a blank form
        form = ClassifiedAdForm()
    else:
        # process data
        form = ClassifiedAdForm(data=request.POST)
        if form.is_valid():
            form.save()
            return redirect('classifieds:categories')
    context = {'form': form}
    return render(request, 'classifieds/new_ad.html', context)


def individual_ad(request, ad_id):
    """View an individual ad on it's own page."""
    obj = ClassifiedAd.objects.get(id=ad_id)
    context = {'category': obj.category, 'headline': obj.headline,
               'body': obj.body, 'email': obj.email, 'date': obj.date_added,
               'title': f'Classifieds - {obj.category} - {obj.headline}'}
    return render(request, 'classifieds/individual_ad.html', context)

discussions/views.py
from django.shortcuts import render

from .models import Topic

# Create your views here.

def index(request):
    """The home page for discussions."""
    return render(request, 'discussions/index.html')

def topics(request):
    """Show all topics."""
    topics = Topic.objects.order_by('date_added')
    context = {'topics':topics}
    return render(request, 'discussions/topics.html', context)

homepage/views.py
from django.shortcuts import render

# Create your views here.

def index(request):
    """The home page for homepage. The main site homepage."""
    return render(request, 'homepage/index.html')

classifieds/templates/classifieds/base.html
{% extends 'homepage/base.html' %}
{% block title %}{{title}}{% endblock title %}
{% block subnav %}
<p>
<a href="{% url 'classifieds:categories' %}">Categories</a>
</p>

{% endblock subnav %}
{% block content %}hello{% endblock content %}

classifieds/templates/classifieds/categories.html
{% extends "classifieds/base.html" %}

{% block content %}
<p>Categories</p>

<ul>
	{% for category in categories %}
	<li><a href="{% url 'classifieds:category' category.id %}">{{category}}</a></li>
	{% empty %}
	<li>No categories exist yet.</li>
	{% endfor %}
</ul>
<a href="{% url 'classifieds:new_ad' %}">Create a new ad</a>
{% endblock content %}

classifieds/templates/classifieds/category.html
{% extends 'classifieds/base.html' %}
{% block content %}
<p>Category: {{category}}</p>
<p>Ads:</p>
<ul>
	{% for ad in entries %}
	<li>
		<a href="{% url 'classifieds:individual_ad' ad.id %}"><p>{{ad.headline}}</a></p>
		<blockquote>
			<p>{{ad.body|slice:":50"}}...</p>
		</blockquote>
		<p>{{ad.date_added|date:'M d, Y H:i'}}</p>
	</li>
	{% empty %}
	<li>There are currently no ads in {{category}}.</li>
	{% endfor %}
</ul>
{% endblock content %}

classifieds/templates/classifieds/index.html
{% extends 'classifieds/base.html' %}
{% block title %}{{title}}{% endblock title %}
{% block content %}
<h1>Classifieds</h1>
<p>Welcome to classifieds.</p>
{% endblock content %}

classifieds/templates/classifieds/individual_ad.html
{% extends 'classifieds/base.html' %}
{% block content %}
<h1>{{headline}}</h1>
<b>{{category}}</b>
<p>{{body|wordwrap:100|linebreaks}}</p>
<p>{{email}}</p>
<p>{{date}}</p>
{% endblock content %}

classifieds/templates/classifieds/new_ad.html
{% extends "classifieds/base.html" %}
{% block content %}
<p>Create new Ad:</p>
<form action="{% url 'classifieds:new_ad' %}" method='post'>
	{% csrf_token %}
	{{form.as_p}}
	<button name="submit">Create Ad</button>
</form>
{% endblock content %}

discussions/templates/discussions/base.html
{% extends "homepage/base.html" %}
{% block title %}
Discussions - Main 
{% endblock title %}

{% block content %}
{% endblock content %}

discussions/templates/discussions/index.html
{% extends "discussions/base.html" %}
{% block content %}
<p>
<a href="{% url 'discussions:topics' %}">Topics</a>
</p>
<br>Discussions</p>
<p>Discussions about worldbuilding.</p>
{% endblock content %}

discussions/templates/discussions/topics.html
{% extends "homepage/base.html" %}
{% block title %}Discussions - Topics{% endblock title %}
{% block content %}
<p>Topics</p>
<ul>
	{% for topic in topics %}
	<li>{{topic}}</li>
	{% empty %}
	<li>No topics have been added yet.</li>
	{% endfor %}
</ul>
{% endblock content %}

homepage/templates/homepage/base.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width,
		initial-scale=1.0">
		<title>{% block title %}{% endblock %}</title>
	</head>
	<body>
		{% block navbar %}
		<div id="navbar">
			<p>
			<br><a href="{% url 'homepage:index' %}">Home Page</a>
			<br><a href="{% url 'classifieds:index' %}">Classifieds</a>
			<br><a href="{% url 'discussions:index' %}">Discussions</a>
			<br><a href="{% url 'admin:index' %}">Admin Panel</a>
			</p>
		</div>
		{% endblock navbar %}
		{% block subnav %}{%endblock subnav %}

{% block content %} {% endblock content %}
	</body>
</html>

homepage/templates/homepage/index.html
{% extends "homepage/base.html" %}
{% block title %}Home Page{% endblock title %}
{% block content %}
<p>HOME PAGE</p>
<h1>Welcome to WorldBuilding.test</h1>
<p>That's right, WorldBuilding.test, where the world is made up and the
points don't matter.
</p><p>
I'm your host Allison Drewson.
</p>
{% endblock content %}